[package]
name = "scribe-crab"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.1.5", features = [
    "client",
    "macros",
    "server",
    "transport-io",
] }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.44.1"
tracing = "0.1.41"
